### ISSUE TITLE
Submit archives

### ISSUE THREAD

**Issue by upintheairsheep** [CatsLover2006/iOSobscuraServer#1]
Hello, may you please add the ability to submit custom archive.org links when it comes back up, plus a scrape of the internet archive’s IPA archive category? The Internet Archive’s auto generated torrents should additionally be linked. Additionally, can you add the ability to scrape open directories for IPA files for now, and open google drive folders via rclone technology? I think there’s a few other supported public folders as well. Also let us view the hashes and link the virustotal results as well for all links.

**Comment by CatsLover2006** [comment]
Custom archive.org links will be easy, I plan to have a list of archive.org xml file lists in a configuration file at some point. Other things will be more difficult with the way the program is currently implemented (especially anything involving Google Drive, as the server stores practically no data by itself)

**Comment by upintheairsheep** [comment]
The Google drive thing will be done by rclone.

**Comment by upintheairsheep** [comment]
> Custom archive.org links will be easy, I plan to have a list of archive.org xml file lists in a configuration file at some point. Other things will be more difficult with the way the program is currently implemented (especially anything involving Google Drive, as the server stores practically no data by itself)

But once rclone is supported, you could easily support crawling through FTPs that contain IPAs. Additionally, you will need to detect encrypted IPAs, which can be cracked through via a bug on iOS 6, but for IPAs that require iOS 7 or higher to run, the IPAs are unusable except for extracting assets out of them, unless someone finds a way to trick it to run on iOS 6, or if quantum computers become usable enough to be able to decrypt them.

**Comment by upintheairsheep** [comment]
Update: the internet archive has finally returned

**Comment by CatsLover2006** [comment]
In order to support rclone, I’d need a server which could take in rclone data, and either output an IPA file or a redirect to the IPA file, and it’d need to be accessible over HTTP or (preferably) HTTPS. While this isn’t impossible, it’d be a lot easier to create a separate server for that and point the existing systems to a URL on that server.

**Comment by upintheairsheep** [comment]
I only recently checked out the source of the system.

**Comment by upintheairsheep** [comment]
Nevermind, https://github.com/KoalaBear84/OpenDirectoryDownloader/ is a
much better thing for open directories.

**Comment by CatsLover2006** [comment]
New archives (not archive groups, I'll figure that out soon) can be added using `config.json`.

**Comment by upintheairsheep** [comment]
I want the ability to submit links directly via the website.

**Comment by upintheairsheep** [comment]
Submit either a direct ipa link, a website/directory that links to various IPAs (use the directory scrape tool or just extract the .ipa links on the page although it will not be recursive), or an internet archive item. When the IA becomes stable enough, we should scrape the archive.

**Comment by CatsLover2006** [comment]
I could add the ability to email the instance admin about the possibility of adding an archive or individual URL, but the idea of adding an IPA file directly via the website could be dangerous. Bad actors could very easily abuse it to flood an instance with viruses.

**Comment by upintheairsheep** [comment]
Integrate VirusTotal for this reason, and have a review system as well (you
need to approve them first). Would fix the problem, also put a warning for
user-submitted applications. Additionally, add hCaptia to prevent spam.

**Comment by upintheairsheep** [comment]
But except on the main instance, leave it disabled 


Sent from my Apple Watch

**Comment by upintheairsheep** [comment]
The issue should be reopened, as I have put counter-abuse methods like hCaptia and manual review (you have to manually VirusTotal it)
