### ISSUE TITLE
URGENT BUG

### ISSUE THREAD

**Issue by upintheairsheep** [CatsLover2006/iOSobscuraServer#12]
Hello, can you please fix the pre-binary phrasing IPAs, the IPA collections added before the binary phrasing update. Please fix it by ignoring the lack of the filesize and architectures. Again, ALL APPS ADDED BEFORE THE BINARY PHRASING UPDATE HAVE VANISHED FROM THE LIST!

This has not been fixed in days.

**Comment by CatsLover2006** [comment]
This was due in part to an untimely failure of my primary machine. I’ve started the parser on my secondary machine.
