### ISSUE TITLE
Early Flat theme

### ISSUE THREAD

**Issue by upintheairsheep** [CatsLover2006/iOSobscuraServer#14]
Hello, can you add an early flat design theme for iOS 7-10 devices using the site to sideload apps and would like the site to look more native to them, although most of the users (including me) prefer skeumorphism, and more than half of users use iOS 1-6? Of course, I'm not saying to remove skeumorphic interface, but make a flat theme that is default for devices running iOS 7 to 10, which use the early flat design.

**Comment by CatsLover2006** [comment]
Due to the way cytyle (the CSS framework I’m using) and the server works, this is practically impossible.

**Comment by CatsLover2006** [comment]
Actually, this might be possible. I’ll code it up this weekend, I have midterms this week and I need to study for them

**Comment by CatsLover2006** [comment]
I was bored, finished it. It defaults to the iOS 6 theme, and will swap to the iOS 7 theme on iOS 7 and later, and on macOS 10.10 and later (unless you're using Firefox which uses an atypical user agent). This likely comes with a funny quirk, where iOS 7 will swap to the iOS 6 theme when you request the desktop site, but that's more a funny quirk than a bug (and it's not like I can really do anything about it, short of having Mavericks use the iOS 7 theme). If the user agent isn't for iOS or macOS, it'll default to the iOS 6 theme.

**Comment by upintheairsheep** [comment]
Now simply fix the search icon.

**Comment by CatsLover2006** [comment]
Search icon will remain the same, it’s an asset and finding another one will be a pain in the ass.
