### ISSUE TITLE
How to run this server actually on a VDS?

### ISSUE THREAD

**Issue by theca1n** [CatsLover2006/iOSobscuraServer#3]
title says it all

**Comment by theca1n** [comment]
When trying opening main.java:

Main.java:3: error: package ca.litten.ios_obscura_server.backend does not exist
import ca.litten.ios_obscura_server.backend.AppList;
                                           ^
Main.java:4: error: package ca.litten.ios_obscura_server.frontend does not exist
import ca.litten.ios_obscura_server.frontend.Server;
                                            ^
Main.java:5: error: package ca.litten.ios_obscura_server.parser does not exist
import ca.litten.ios_obscura_server.parser.AppDownloader;
                                          ^
Main.java:6: error: package ca.litten.ios_obscura_server.parser does not exist
import ca.litten.ios_obscura_server.parser.ArchiveListDecoder;
                                          ^
Main.java:7: error: package com.google.common.escape does not exist
import com.google.common.escape.Escaper;
                               ^
Main.java:18: error: package com.google.common.net does not exist
import static com.google.common.net.UrlEscapers.urlPathSegmentEscaper;
                                   ^
Main.java:18: error: static import only from classes and interfaces
import static com.google.common.net.UrlEscapers.urlPathSegmentEscaper;
^
Main.java:115: error: cannot find symbol
    private static Server server;
                   ^
  symbol:   class Server
  location: class Main
Main.java:56: error: cannot find symbol
            Escaper escaper = urlPathSegmentEscaper();
            ^
  symbol:   class Escaper
  location: class ArchiveParser
Main.java:56: error: cannot find symbol
            Escaper escaper = urlPathSegmentEscaper();
                              ^
  symbol:   method urlPathSegmentEscaper()
  location: class ArchiveParser
Main.java:60: error: cannot find symbol
                urlist.addAll(Arrays.asList(ArchiveListDecoder.getUrlListFromArchiveOrgListing(url)));
                                            ^
  symbol:   variable ArchiveListDecoder
  location: class ArchiveParser
Main.java:78: error: cannot find symbol
                        good = AppList.appUrlAlreadyExists(url);
                               ^
  symbol:   variable AppList
  location: class ArchiveParser
Main.java:89: error: cannot find symbol
                        AppDownloader.downloadAndAddApp(new URL(finalUrl));
                        ^
  symbol:   variable AppDownloader
  location: class ArchiveParser
Main.java:118: error: cannot find symbol
        AppList.loadAppDatabaseFile(new File("db.json"));
        ^
  symbol:   variable AppList
  location: class Main
Main.java:127: error: cannot find symbol
                server = new Server(new InetSocketAddress(port));
                             ^
  symbol:   class Server
  location: class Main
Main.java:134: error: cannot find symbol
            Server.allowReload = false;
            ^
  symbol:   variable Server
  location: class Main
Main.java:143: error: cannot find symbol
                        AppList.saveAppDatabaseFile(new File("db.json"));
                        ^
  symbol:   variable AppList
  location: class Main
Main.java:147: error: cannot find symbol
                    AppList.saveAppDatabaseFile(new File("db.json"));
                    ^
  symbol:   variable AppList
  location: class Main
Main.java:151: error: cannot find symbol
            Server.allowReload = true;
            ^
  symbol:   variable Server
  location: class Main
19 errors
error: compilation failed

**Comment by CatsLover2006** [comment]
You did something very wrong. I’ll create a zip file with everything required as a release soon.
