### ISSUE TITLE
List architecture, hashes, and virustotal

### ISSUE THREAD

**Issue by upintheairsheep** [CatsLover2006/iOSobscuraServer#6]
Hello, can you add the architecture of the app (ARMv6-only, ARMv7-only, hybrid ARM, x86, x86_64) (32bit-only, 64bit-only, compatible with both 32 and 64 bits, x86 Simulator build, x64 simulator build), the encryption status (iOS 6 bug allows you to decrypt iOS 6-compatible encrypted apps), list the hashes, and the VirusTotal link? The encryption status is especially important.

**Comment by Tomus1236** [comment]
No, but instead can you add "seychells-big-mega-.ipa-collection-ios-apps-and-games" to config.json for even more apps

**Comment by Tomus1236** [comment]
> No, but instead can you add "seychells-big-mega-.ipa-collection-ios-apps-and-games" to config.json for even more apps

Please CatsLover2006

**Comment by CatsLover2006** [comment]
`config.json` is a configuration file, it’s meant to be modified by instance administrators. I can add it to the default, though.

**Comment by upintheairsheep** [comment]
r/youngpeoplegithub

**Comment by CatsLover2006** [comment]
Also, listing architectures and detecting encryption status would require parsing the executable of the app, a very daunting task in Java. A virustotal link would be fairly easy, but it would require a virustotal API key, and would be easily overloaded. It’d be easier to add an option to copy the URL to your clipboard to make pasting it into virustotal easy.

**Comment by Tomus1236** [comment]
> `config.json` is a configuration file, it’s meant to be modified by instance administrators. I can add it to the default, though.

Ok thank you add the apps from this archive.org page

**Comment by CatsLover2006** [comment]
> > `config.json` is a configuration file, it’s meant to be modified by instance administrators. I can add it to the default, though.
> 
> Ok thank you add the apps from this archive.org page

I will when I get back to my computer, I’m currently away from my computer.

**Comment by upintheairsheep** [comment]
> Also, listing architectures and detecting encryption status would require parsing the executable of the app, a very daunting task in Java. A virustotal link would be fairly easy, but it would require a virustotal API key, and would be easily overloaded. It’d be easier to add an option to copy the URL to your clipboard to make pasting it into virustotal easy.

I am aware of this, but a possible solution could be to tell Java to execute some non-Java tool that could do it, but it would make dependencies heavier, so it could be disabled by default by hosts. The encryption detection is especially important, as encrypted apps are unusable on all iOS versions except iOS 6 (via a bug which conveniently was not patched till iOS 7, the first flat version of iOS, and most people jailbreaking a legacy device would choose the latest iOS 6 version, but many devices aren’t compatible with 6).

**Comment by upintheairsheep** [comment]
> Also, listing architectures and detecting encryption status would require parsing the executable of the app, a very daunting task in Java. A virustotal link would be fairly easy, but it would require a virustotal API key, and would be easily overloaded. It’d be easier to add an option to copy the URL to your clipboard to make pasting it into virustotal easy.

Also, before I forget, the filesize and possibly the file’s timestamps should be added as well.

**Comment by CatsLover2006** [comment]
> I am aware of this, but a possible solution could be to tell Java to execute some non-Java tool that could do it

I don't know if such a tool exists, outside of manually checking using an iOS device. If such a tool existed, I don't know about it.

**Comment by CatsLover2006** [comment]
Also, one other thing of note: I never actually download an app onto a permanent storage device. I keep the app in RAM long enough to parse its metadata, and then discard everything but the metadata. An external tool wouldn't work with this in mind.

**Comment by upintheairsheep** [comment]
I guessed that already 


Sent from my Apple Watch

**Comment by CatsLover2006** [comment]
I've looked up the macOS (and, by extension, iOS) executable header format; if I treat the header as a byte stream, parsing it should be fairly straightforward. Problem will be figuring out which file that is if it is found before info.plist

**Comment by upintheairsheep** [comment]
Does this include encryption?

**Comment by CatsLover2006** [comment]
No, this does not include encryption. I would only be able to check what architectures are supported.

**Comment by upintheairsheep** [comment]
> Also, one other thing of note: I never actually download an app onto a permanent storage device. I keep the app in RAM long enough to parse its metadata, and then discard everything but the metadata. An external tool wouldn't work with this in mind.

Since most of the apps are on the internet archive, filesize and datestamps can be found in the metadata xml. There is enough metadata of the existing apps.

**Comment by upintheairsheep** [comment]
> No, this does not include encryption. I would only be able to check what architectures are supported.

The iOS Obscura and LegacyJailbreak communities are there to assist you.

**Comment by CatsLover2006** [comment]
I stand corrected, it turns out it is possible to detect encryption thanks to the fact that it's a load command in the binary.
I'm gonna start working on this in its own branch.

**Comment by upintheairsheep** [comment]
> I stand corrected, it turns out it is possible to detect encryption thanks to the fact that it's a load command in the binary. I'm gonna start working on this in its own branch.

OK, the filesize will be necessary as well

**Comment by CatsLover2006** [comment]
Complete (sans virustotal due to api limits)

**Comment by upintheairsheep** [comment]
> Complete (sans virustotal due to api limits)

URGENT: Hello, can you please fix the pre-binary phrasing IPAs. Please fix it by ignoring her lack of the filesize and architectures. Again, MOST APPS HAVE VANISHED FROM THE LIST!
