### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by upintheairsheep** [CatsLover2006/iOSobscuraServer#9]
Add a "blacklist" of apps configurable in case of any DMCA. The DMCA will only prevent the app from being searchable from here and have it's entry hidden, while it is added to a blacklist to prevent it from being public again. A DMCA email should be present on the page, and there has to be reasonable, concrete proof that you are part of the company, no copyright trolls abusing it.

**Comment by CatsLover2006** [comment]
I'm not storing anything, so DMCA should not be an issue; if DMCA should be going anywhere, it should be at the people who're hosting the files I'm parsing

**Comment by upintheairsheep** [comment]
> I'm not storing anything, so DMCA should not be an issue; if DMCA should be going anywhere, it should be at the people who're hosting the files I'm parsing

I know that it there's zero IPA files hosted. On the iPhoneOS Obscura server, the full archive planned to have a DMCA system. A mailto Link (probably to a simplelogin email) will raise a lot less scrutiny to take the site down. The reason a blacklist is needed, is if the hosts take down the app, another person in the future might dump it from their devices and rehost it somewhere else unknowingly, causing the app to pop up on this list (would be an endless game of cat and mouse for copyright if this happens), causing at least some unwanted copyright scrutiny.

**Comment by CatsLover2006** [comment]
In that case, the blacklist still wouldn’t work; the separately dumped app would be at a different URL.

**Comment by upintheairsheep** [comment]
I was meant as a bundle ID blacklist (ex: com.example.app)
